-- 1. XÓA DATABASE CŨ (NẾU CÓ)
USE master;
GO
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'QLCHOTO')
BEGIN
    ALTER DATABASE QLCHOTO SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QLCHOTO;
END
GO

-- 2. TẠO LẠI DATABASE
CREATE DATABASE QLCHOTO;
GO
USE QLCHOTO;
GO

-- 3. CHUYỂN VỀ CHẾ ĐỘ MULTI_USER
ALTER DATABASE QLCHOTO SET MULTI_USER;
GO

-- 4. TẠO BẢNG
CREATE TABLE SANPHAM (
    IDSP INT IDENTITY(1,1) PRIMARY KEY,
    TenSP NVARCHAR(100) NOT NULL,
    NgaySanXuat DATETIME NULL,
    LoaiXe NVARCHAR(100),
    HangXe NVARCHAR(20),
    GiaBan DECIMAL(18,2),
    SoLuong INT,
    HinhAnh VARBINARY(MAX)
);
GO

CREATE TABLE THONGTIN (
    IDKH INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATETIME,
    GioiTinh CHAR(3) CHECK (GioiTinh IN (N'Nam', N'Nu')),
    SDT NVARCHAR(20),
    DiaChi NVARCHAR(100),
    Gmail NVARCHAR(100)
);
GO

CREATE TABLE NHANVIEN (
    IDNV INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    SDT NVARCHAR(10),
    Gmail NVARCHAR(100),
    ChucVu NVARCHAR(1000)
);
GO

CREATE TABLE HOADON (
    IDHD INT IDENTITY(1,1) PRIMARY KEY,
    IDKH INT NOT NULL,
    IDNV INT NOT NULL,
    NgayMua DATETIME,
    ThanhTien DECIMAL(18,2),
    SoLuong INT,
    FOREIGN KEY (IDKH) REFERENCES THONGTIN(IDKH),
    FOREIGN KEY (IDNV) REFERENCES NHANVIEN(IDNV)
);
GO

CREATE TABLE CHITIETDONHANG (
    IDCTDH INT IDENTITY(1,1) PRIMARY KEY,
    IDHD INT NOT NULL,
    IDSP INT NOT NULL,
    DonGia DECIMAL(18,2),
    ThanhTien DECIMAL(18,2),
    SoLuong INT,
    FOREIGN KEY (IDHD) REFERENCES HOADON(IDHD) ON DELETE CASCADE,
    FOREIGN KEY (IDSP) REFERENCES SANPHAM(IDSP)
);
GO

CREATE TABLE TAIKHOAN (
    IDTK INT IDENTITY(1,1) PRIMARY KEY,
    IDKH INT NOT NULL,
    TenTK NVARCHAR(100) NOT NULL,
    MatKhau NVARCHAR(100) NOT NULL,
    Gmail NVARCHAR(100),
    Role NVARCHAR(20) NOT NULL DEFAULT N'user',
    ResetToken NVARCHAR(100),
    TokenExpiry DATETIME,
    FOREIGN KEY (IDKH) REFERENCES THONGTIN(IDKH)
);
GO

CREATE TABLE DANHGIA (
    IDDG INT IDENTITY(1,1) PRIMARY KEY,
    IDKH INT NOT NULL,
    IDSP INT NOT NULL,
    ThangDiem INT,
    FeedBack NVARCHAR(1000),
    NgayFB DATETIME,
    FOREIGN KEY (IDKH) REFERENCES THONGTIN(IDKH),
    FOREIGN KEY (IDSP) REFERENCES SANPHAM(IDSP)
);
GO

CREATE TABLE BAOHANH (
    IDBH INT IDENTITY(1,1) PRIMARY KEY,
    IDSP INT NOT NULL,
    NgayMua DATETIME,
    NgayHHBH DATETIME,
    NoiDung NVARCHAR(1000),
    FOREIGN KEY (IDSP) REFERENCES SANPHAM(IDSP)
);
GO

CREATE TABLE ThongBao (
    IDTB INT IDENTITY(1,1) PRIMARY KEY,
    TenTB CHAR(10),
    NoiDungTB NVARCHAR(1000),
    NgayDang DATETIME,
    TinhTrang NVARCHAR(100),
    IDNV INT,
    IDKH INT,
    FOREIGN KEY (IDNV) REFERENCES NHANVIEN(IDNV),
    FOREIGN KEY (IDKH) REFERENCES THONGTIN(IDKH)
);
GO

CREATE TABLE LOG_DANGNHAP (
    IDLog INT IDENTITY(1,1) PRIMARY KEY,
    IDTK INT NOT NULL,
    ThoiGian DATETIME2,
    IP VARCHAR(50),
    ThanhCong BIT,
    FOREIGN KEY (IDTK) REFERENCES TAIKHOAN(IDTK)
);
GO

CREATE TABLE THONGKE_SLBAN (
    IDSP INT NOT NULL,
    SoLuongBan INT,
    ThoiGian DATETIME NOT NULL,
    PRIMARY KEY (IDSP, ThoiGian),
    FOREIGN KEY (IDSP) REFERENCES SANPHAM(IDSP)
);
GO

-- 5. TẠO TÀI KHOẢN ADMIN (với password đã mã hóa bằng BCrypt)


INSERT INTO THONGTIN (HoTen, NgaySinh, GioiTinh, SDT, DiaChi, Gmail)
VALUES (N'Admin', '1990-01-01', N'Nam', '0123456789', N'Hà Nội', 'bestluluthegio@gmial.com')
GO

DECLARE @AdminID INT = SCOPE_IDENTITY();
INSERT INTO TAIKHOAN (IDKH, TenTK, MatKhau, Gmail, Role)
VALUES (
    @AdminID,
    N'admin',
    N'$2a$11$9mV5zvUPh0Zc7sGgiEqkYO7BbUHiK6zydO7Y3dMI.vRkmCmP9b7/y',	
    N'admin@example.com',
    N'admin'
);
GO
UPDATE TAIKHOAN
SET MatKhau = '$2a$11$FUt0NSVOuFtdHKkUxRYnhuHPeJNOLM6zGidznQUQNUi4AApDzNXHe'
WHERE TenTK = 'admin';

SELECT TenTk, MatKhau FROM TAIKHOAN;
-- 6. XEM DỮ LIỆU
SELECT * FROM THONGTIN;
SELECT * FROM TAIKHOAN;
SELECT * FROM LOG_DANGNHAP;
GO
