// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebQuanLiCuaHangBanOto.Models;

public partial class Baohanh
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Idbh { get; set; }

    public int Idsp { get; set; }

    public DateTime? NgayMua { get; set; }

    public DateTime? NgayHhbh { get; set; }

    public string NoiDung { get; set; }

    public virtual Sanpham IdspNavigation { get; set; }
}