// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebQuanLiCuaHangBanOto.Models;

public partial class Chitietdonhang
{
    public int Idctdh { get; set; }

    public int Idhd { get; set; }

    public int Idsp { get; set; }

    public decimal? DonGia { get; set; }

    public decimal? ThanhTien { get; set; }

    public int? SoLuong { get; set; }

    public virtual Hoadon IdhdNavigation { get; set; }

    public virtual Sanpham IdspNavigation { get; set; }
}