// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebQuanLiCuaHangBanOto.Models;

public partial class Danhgia
{
    public int Iddg { get; set; }

    public int Idkh { get; set; }

    public int Idsp { get; set; }

    public int? ThangDiem { get; set; }

    public string FeedBack { get; set; }

    public DateTime? NgayFb { get; set; }

    public virtual Thongtin IdkhNavigation { get; set; }

    public virtual Sanpham IdspNavigation { get; set; }
}