// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebQuanLiCuaHangBanOto.Models;

public partial class Hoadon
{
    public int Idhd { get; set; }

    public int Idkh { get; set; }

    public int Idnv { get; set; }

    public DateTime? NgayMua { get; set; }

    public decimal? ThanhTien { get; set; }

    public int? SoLuong { get; set; }

    public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; } = new List<Chitietdonhang>();

    public virtual Thongtin IdkhNavigation { get; set; }

    public virtual Nhanvien IdnvNavigation { get; set; }
}