// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebQuanLiCuaHangBanOto.Models;

public partial class LogDangnhap
{
    public int Idlog { get; set; }

    public int Idtk { get; set; }

    public DateTime? ThoiGian { get; set; }

    public string Ip { get; set; }

    public bool? ThanhCong { get; set; }

    public virtual Taikhoan IdtkNavigation { get; set; }
}