// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebQuanLiCuaHangBanOto.Models;

public partial class Nhanvien
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Idnv { get; set; }

    public string HoTen { get; set; }

    public string Sdt { get; set; }

    public string Gmail { get; set; }

    public string ChucVu { get; set; }

    public virtual ICollection<Hoadon> Hoadons { get; set; } = new List<Hoadon>();

    public virtual ICollection<ThongBao> ThongBaos { get; set; } = new List<ThongBao>();
}