// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebQuanLiCuaHangBanOto.Models;

public partial class QLCHOTOContext : DbContext
{
    public QLCHOTOContext(DbContextOptions<QLCHOTOContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Baohanh> Baohanhs { get; set; }

    public virtual DbSet<Chitietdonhang> Chitietdonhangs { get; set; }

    public virtual DbSet<Dangnhap> Dangnhaps { get; set; }

    public virtual DbSet<Danhgia> Danhgia { get; set; }

    public virtual DbSet<Hoadon> Hoadons { get; set; }

    public virtual DbSet<LogDangnhap> LogDangnhaps { get; set; }

    public virtual DbSet<Nhanvien> Nhanviens { get; set; }

    public virtual DbSet<Sanpham> Sanphams { get; set; }

    public virtual DbSet<Taikhoan> Taikhoans { get; set; }

    public virtual DbSet<ThongBao> ThongBaos { get; set; }

    public virtual DbSet<ThongkeSlban> ThongkeSlbans { get; set; }

    public virtual DbSet<Thongtin> Thongtins { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Baohanh>(entity =>
        {
            entity.HasKey(e => e.Idbh).HasName("PK__BAOHANH__B87DA8DF7DA58F41");

            entity.ToTable("BAOHANH");

            entity.Property(e => e.Idbh)
                .ValueGeneratedNever()
                .HasColumnName("IDBH");
            entity.Property(e => e.Idsp).HasColumnName("IDSP");
            entity.Property(e => e.NgayHhbh)
                .HasColumnType("datetime")
                .HasColumnName("NgayHHBH");
            entity.Property(e => e.NgayMua).HasColumnType("datetime");
            entity.Property(e => e.NoiDung).HasMaxLength(1000);

            entity.HasOne(d => d.IdspNavigation).WithMany(p => p.Baohanhs)
                .HasForeignKey(d => d.Idsp)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BAOHANH__IDSP__4D94879B");
        });

        modelBuilder.Entity<Chitietdonhang>(entity =>
        {
            entity.HasKey(e => e.Idctdh).HasName("PK__CHITIETD__0F87803D487B3585");

            entity.ToTable("CHITIETDONHANG");

            entity.Property(e => e.Idctdh)
                .ValueGeneratedNever()
                .HasColumnName("IDCTDH");
            entity.Property(e => e.DonGia).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Idhd).HasColumnName("IDHD");
            entity.Property(e => e.Idsp).HasColumnName("IDSP");
            entity.Property(e => e.ThanhTien).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.IdhdNavigation).WithMany(p => p.Chitietdonhangs)
                .HasForeignKey(d => d.Idhd)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CHITIETDON__IDHD__4222D4EF");

            entity.HasOne(d => d.IdspNavigation).WithMany(p => p.Chitietdonhangs)
                .HasForeignKey(d => d.Idsp)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CHITIETDON__IDSP__4316F928");
        });

        modelBuilder.Entity<Dangnhap>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Dangnhap__3214EC0744331A16");

            entity.ToTable("Dangnhap");

            entity.HasIndex(e => e.Username, "UQ_Dangnhap_Username").IsUnique();

            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Danhgia>(entity =>
        {
            entity.HasKey(e => e.Iddg).HasName("PK__DANHGIA__B87DB89BAA82AE31");

            entity.ToTable("DANHGIA");

            entity.Property(e => e.Iddg)
                .ValueGeneratedNever()
                .HasColumnName("IDDG");
            entity.Property(e => e.FeedBack).HasMaxLength(1000);
            entity.Property(e => e.Idkh).HasColumnName("IDKH");
            entity.Property(e => e.Idsp).HasColumnName("IDSP");
            entity.Property(e => e.NgayFb)
                .HasColumnType("datetime")
                .HasColumnName("NgayFB");

            entity.HasOne(d => d.IdkhNavigation).WithMany(p => p.Danhgia)
                .HasForeignKey(d => d.Idkh)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DANHGIA__IDKH__49C3F6B7");

            entity.HasOne(d => d.IdspNavigation).WithMany(p => p.Danhgia)
                .HasForeignKey(d => d.Idsp)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DANHGIA__IDSP__4AB81AF0");
        });

        modelBuilder.Entity<Hoadon>(entity =>
        {
            entity.HasKey(e => e.Idhd).HasName("PK__HOADON__B87C1A073D0F24BF");

            entity.ToTable("HOADON");

            entity.Property(e => e.Idhd)
                .ValueGeneratedNever()
                .HasColumnName("IDHD");
            entity.Property(e => e.Idkh).HasColumnName("IDKH");
            entity.Property(e => e.Idnv).HasColumnName("IDNV");
            entity.Property(e => e.NgayMua).HasColumnType("datetime");
            entity.Property(e => e.ThanhTien).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.IdkhNavigation).WithMany(p => p.Hoadons)
                .HasForeignKey(d => d.Idkh)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__HOADON__IDKH__3E52440B");

            entity.HasOne(d => d.IdnvNavigation).WithMany(p => p.Hoadons)
                .HasForeignKey(d => d.Idnv)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__HOADON__IDNV__3F466844");
        });

        modelBuilder.Entity<LogDangnhap>(entity =>
        {
            entity.HasKey(e => e.Idlog).HasName("PK__LOG_DANG__95D0020876375A16");

            entity.ToTable("LOG_DANGNHAP");

            entity.Property(e => e.Idlog)
                .ValueGeneratedNever()
                .HasColumnName("IDLog");
            entity.Property(e => e.Idtk).HasColumnName("IDTK");
            entity.Property(e => e.Ip)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("IP");

            entity.HasOne(d => d.IdtkNavigation).WithMany(p => p.LogDangnhaps)
                .HasForeignKey(d => d.Idtk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LOG_DANGNH__IDTK__5441852A");
        });

        modelBuilder.Entity<Nhanvien>(entity =>
        {
            entity.HasKey(e => e.Idnv).HasName("PK__NHANVIEN__B87DC9B2224B52B0");

            entity.ToTable("NHANVIEN");

            entity.Property(e => e.Idnv)
                .ValueGeneratedNever()
                .HasColumnName("IDNV");
            entity.Property(e => e.ChucVu).HasMaxLength(1000);
            entity.Property(e => e.Gmail).HasMaxLength(100);
            entity.Property(e => e.HoTen)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Sdt)
                .HasMaxLength(10)
                .HasColumnName("SDT");
        });

        modelBuilder.Entity<Sanpham>(entity =>
        {
            entity.HasKey(e => e.Idsp).HasName("PK__SANPHAM__B87C02A5FF9B5965");

            entity.ToTable("SANPHAM");

            entity.Property(e => e.Idsp)
                .ValueGeneratedNever()
                .HasColumnName("IDSP");
            entity.Property(e => e.GiaBan).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.HangXe).HasMaxLength(20);
            entity.Property(e => e.LoaiXe).HasMaxLength(100);
            entity.Property(e => e.NgaySanXuat).HasColumnType("datetime");
            entity.Property(e => e.TenSp)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("TenSP");
        });

        modelBuilder.Entity<Taikhoan>(entity =>
        {
            entity.HasKey(e => e.Idtk).HasName("PK__TAIKHOAN__B87C3A839D2944D6");

            entity.ToTable("TAIKHOAN");

            entity.Property(e => e.Idtk)
                .ValueGeneratedNever()
                .HasColumnName("IDTK");
            entity.Property(e => e.Gmail).HasMaxLength(100);
            entity.Property(e => e.Idkh).HasColumnName("IDKH");
            entity.Property(e => e.MatKhau)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("user");
            entity.Property(e => e.TenTk)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("TenTK");

            entity.HasOne(d => d.IdkhNavigation).WithMany(p => p.Taikhoans)
                .HasForeignKey(d => d.Idkh)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TAIKHOAN__IDKH__46E78A0C");
        });

        modelBuilder.Entity<ThongBao>(entity =>
        {
            entity.HasKey(e => e.Idtb).HasName("PK__ThongBao__B87C3A8AA18CF203");

            entity.ToTable("ThongBao");

            entity.Property(e => e.Idtb)
                .ValueGeneratedNever()
                .HasColumnName("IDTB");
            entity.Property(e => e.Idkh).HasColumnName("IDKH");
            entity.Property(e => e.Idnv).HasColumnName("IDNV");
            entity.Property(e => e.NgayDang).HasColumnType("datetime");
            entity.Property(e => e.NoiDungTb)
                .HasMaxLength(1000)
                .HasColumnName("NoiDungTB");
            entity.Property(e => e.TenTb)
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("TenTB");
            entity.Property(e => e.TinhTrang).HasMaxLength(100);

            entity.HasOne(d => d.IdkhNavigation).WithMany(p => p.ThongBaos)
                .HasForeignKey(d => d.Idkh)
                .HasConstraintName("FK__ThongBao__IDKH__5165187F");

            entity.HasOne(d => d.IdnvNavigation).WithMany(p => p.ThongBaos)
                .HasForeignKey(d => d.Idnv)
                .HasConstraintName("FK__ThongBao__IDNV__5070F446");
        });

        modelBuilder.Entity<ThongkeSlban>(entity =>
        {
            entity.HasKey(e => new { e.Idsp, e.ThoiGian }).HasName("PK__THONGKE___629E62681E0030FF");

            entity.ToTable("THONGKE_SLBAN");

            entity.Property(e => e.Idsp).HasColumnName("IDSP");
            entity.Property(e => e.ThoiGian).HasColumnType("datetime");

            entity.HasOne(d => d.IdspNavigation).WithMany(p => p.ThongkeSlbans)
                .HasForeignKey(d => d.Idsp)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__THONGKE_SL__IDSP__571DF1D5");
        });

        modelBuilder.Entity<Thongtin>(entity =>
        {
            entity.HasKey(e => e.Idkh).HasName("PK__THONGTIN__B87DC1A787116926");

            entity.ToTable("THONGTIN");

            entity.Property(e => e.Idkh)
                .ValueGeneratedNever()
                .HasColumnName("IDKH");
            entity.Property(e => e.DiaChi).HasMaxLength(100);
            entity.Property(e => e.GioiTinh)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Gmail).HasMaxLength(100);
            entity.Property(e => e.HoTen)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NgaySinh).HasColumnType("datetime");
            entity.Property(e => e.Sdt)
                .HasMaxLength(20)
                .HasColumnName("SDT");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}