// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebQuanLiCuaHangBanOto.Models;

public partial class Taikhoan
{
    public int Idtk { get; set; }

    public int Idkh { get; set; }

    public string TenTk { get; set; }

    public string MatKhau { get; set; }

    public string Gmail { get; set; }

    public string Role { get; set; }

    public virtual Thongtin IdkhNavigation { get; set; }

    public virtual ICollection<LogDangnhap> LogDangnhaps { get; set; } = new List<LogDangnhap>();
}