// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebQuanLiCuaHangBanOto.Models;

public partial class ThongkeSlban
{
    public int Idsp { get; set; }

    public int? SoLuongBan { get; set; }

    public DateTime ThoiGian { get; set; }

    public virtual Sanpham IdspNavigation { get; set; }
}