// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebQuanLiCuaHangBanOto.Models;

public partial class ThongBao
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Idtb { get; set; }

    public string TenTb { get; set; }

    public string NoiDungTb { get; set; }

    public DateTime? NgayDang { get; set; }

    public string TinhTrang { get; set; }

    public int? Idnv { get; set; }

    public int? Idkh { get; set; }

    public virtual Thongtin IdkhNavigation { get; set; }

    public virtual Nhanvien IdnvNavigation { get; set; }
}